# Generated by Django 3.1 on 2020-11-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
    ]
